// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgL3KXuz_gl6MJcGl3dg000x5Rv2c18vc',
    appId: '1:983757822317:web:5160260ccddc2f345b2264',
    messagingSenderId: '983757822317',
    projectId: 'studymate-6ee53',
    authDomain: 'studymate-6ee53.firebaseapp.com',
    storageBucket: 'studymate-6ee53.firebasestorage.app',
    measurementId: 'G-H6H9Y4DZBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHyYPV8xrs4J0v3sy3RgQfgjziKxUsuSk',
    appId: '1:983757822317:android:b8302632840695765b2264',
    messagingSenderId: '983757822317',
    projectId: 'studymate-6ee53',
    storageBucket: 'studymate-6ee53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGhcGA9Ig53wsEwybMKFpFlx6P4gPuyFo',
    appId: '1:983757822317:ios:f0d5d6d2b1f742515b2264',
    messagingSenderId: '983757822317',
    projectId: 'studymate-6ee53',
    storageBucket: 'studymate-6ee53.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGhcGA9Ig53wsEwybMKFpFlx6P4gPuyFo',
    appId: '1:983757822317:ios:f0d5d6d2b1f742515b2264',
    messagingSenderId: '983757822317',
    projectId: 'studymate-6ee53',
    storageBucket: 'studymate-6ee53.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgL3KXuz_gl6MJcGl3dg000x5Rv2c18vc',
    appId: '1:983757822317:web:153f80eaa72fe5455b2264',
    messagingSenderId: '983757822317',
    projectId: 'studymate-6ee53',
    authDomain: 'studymate-6ee53.firebaseapp.com',
    storageBucket: 'studymate-6ee53.firebasestorage.app',
    measurementId: 'G-LCTHP08GRR',
  );
}
